frames:
- frame_id: 0
  slots:
  - boardname: A123ABCD
    online_offline: ''
    slotid: 0
    status: Normal
    subtype0: ''
    subtype1: ''
  - boardname: ''
    online_offline: ''
    slotid: 1
    status: ''
    subtype0: ''
    subtype1: ''
  - boardname: H901GPSFE
    online_offline: ''
    ports:
    - - config_state: online
        control_flag: active
        description: The boiling consignment budgets.
        match_state: initial
        online_offline: online
        ont_id: 0
        protect_side: 'no'
        run_state: offline
        sn: 46VBSM4LFW7QLGAV
      - config_state: online
        control_flag: configuring
        description: The fretful sweatshop promotes.
        match_state: mismatch
        online_offline: online
        ont_id: 1
        protect_side: 'yes'
        run_state: online
        sn: PBFGXVIPMQZN0E1T
      - config_state: normal
        control_flag: active
        description: The damaging nerve nests.
        match_state: mismatch
        online_offline: offline
        ont_id: 2
        protect_side: 'yes'
        run_state: offline
        sn: X64PWIUVU5TGONE1
      - config_state: online
        control_flag: configuring
        description: The macho quart blinks.
        match_state: mismatch
        online_offline: online
        ont_id: 3
        protect_side: 'yes'
        run_state: online
        sn: ZD53TVQMSXNLUFE3
      - config_state: online
        control_flag: active
        description: The industrious bumper kicks.
        match_state: mismatch
        online_offline: online
        ont_id: 4
        protect_side: 'no'
        run_state: offline
        sn: E8CFIM0QRWMY1YJV
      - config_state: normal
        control_flag: configuring
        description: The understood deviance remembers.
        match_state: initial
        online_offline: offline
        ont_id: 5
        protect_side: 'yes'
        run_state: online
        sn: APWLB7QEY4Y64H11
      - config_state: normal
        control_flag: configuring
        description: The wandering elf assists.
        match_state: initial
        online_offline: online
        ont_id: 6
        protect_side: 'no'
        run_state: offline
        sn: B141LLHVQ18P6AK4
      - config_state: normal
        control_flag: configuring
        description: The deranged echidna glues.
        match_state: match
        online_offline: offline
        ont_id: 7
        protect_side: 'no'
        run_state: online
        sn: 02GVAXHK3LXSZB4B
      - config_state: failing
        control_flag: active
        description: The ancient hunter reinforces.
        match_state: match
        online_offline: offline
        ont_id: 8
        protect_side: 'yes'
        run_state: offline
        sn: DZE8P8SY4R8G0I4P
      - config_state: normal
        control_flag: configuring
        description: The brawny honeydew deserts.
        match_state: match
        online_offline: offline
        ont_id: 9
        protect_side: 'yes'
        run_state: online
        sn: EITYLTDDY2V5ESD6
      - config_state: failing
        control_flag: active
        description: The fanatical twine finances.
        match_state: mismatch
        online_offline: online
        ont_id: 10
        protect_side: 'yes'
        run_state: online
        sn: 50HVGRGSETKS72UH
      - config_state: failing
        control_flag: active
        description: The overconfident dinner heats.
        match_state: match
        online_offline: offline
        ont_id: 11
        protect_side: 'yes'
        run_state: offline
        sn: 6YN1YJYTJZIOLM9Z
      - config_state: online
        control_flag: active
        description: The rotten census sounds.
        match_state: mismatch
        online_offline: offline
        ont_id: 12
        protect_side: 'no'
        run_state: online
        sn: Q5P60X5F3EEJ60RA
      - config_state: normal
        control_flag: active
        description: The lavish gun strengthens.
        match_state: initial
        online_offline: offline
        ont_id: 13
        protect_side: 'no'
        run_state: offline
        sn: T5LNUJTG0HPTJ91W
      - config_state: failing
        control_flag: active
        description: The gusty sari coordinates.
        match_state: match
        online_offline: offline
        ont_id: 14
        protect_side: 'no'
        run_state: online
        sn: E2ZSGR9G6JZRPZDF
      - config_state: normal
        control_flag: configuring
        description: The acrid shallot extends.
        match_state: initial
        online_offline: online
        ont_id: 15
        protect_side: 'no'
        run_state: offline
        sn: 1OJNON01PVSX1ZV3
    - - config_state: normal
        control_flag: configuring
        description: The sable foreigner operates.
        match_state: match
        online_offline: offline
        ont_id: 0
        protect_side: 'no'
        run_state: offline
        sn: JDAW7W6DILN4I7NM
      - config_state: failing
        control_flag: active
        description: The assorted expansionism drafts.
        match_state: mismatch
        online_offline: offline
        ont_id: 1
        protect_side: 'no'
        run_state: online
        sn: KX1JLAVA1O1VA6WN
      - config_state: online
        control_flag: active
        description: The unequaled hanger forsakes.
        match_state: match
        online_offline: offline
        ont_id: 2
        protect_side: 'no'
        run_state: offline
        sn: 27UQDK92RZRL8AVF
      - config_state: normal
        control_flag: configuring
        description: The kindhearted granddaughter spares.
        match_state: initial
        online_offline: online
        ont_id: 3
        protect_side: 'yes'
        run_state: offline
        sn: 4HVUX6OBBDCUELAA
      - config_state: normal
        control_flag: configuring
        description: The guiltless aftermath punctures.
        match_state: match
        online_offline: offline
        ont_id: 4
        protect_side: 'yes'
        run_state: offline
        sn: 6ZLN3PU3LQM1N8CK
      - config_state: failing
        control_flag: configuring
        description: The abiding cyclamen rates.
        match_state: initial
        online_offline: online
        ont_id: 5
        protect_side: 'yes'
        run_state: offline
        sn: IPLXDRA7JZ1ZFNGC
      - config_state: failing
        control_flag: active
        description: The voiceless planula tests.
        match_state: match
        online_offline: offline
        ont_id: 6
        protect_side: 'no'
        run_state: offline
        sn: ECMF50TNSYBIY4J1
      - config_state: normal
        control_flag: configuring
        description: The amuck yew breathes.
        match_state: mismatch
        online_offline: offline
        ont_id: 7
        protect_side: 'yes'
        run_state: offline
        sn: GIK2DX4A4CWKJROX
      - config_state: online
        control_flag: configuring
        description: The nutty chip worries.
        match_state: match
        online_offline: online
        ont_id: 8
        protect_side: 'yes'
        run_state: online
        sn: TDGYIPVZY8T6BA50
      - config_state: failing
        control_flag: configuring
        description: The plastic reindeer forms.
        match_state: mismatch
        online_offline: offline
        ont_id: 9
        protect_side: 'yes'
        run_state: online
        sn: O3HJGICKYUXEG0N9
      - config_state: failing
        control_flag: configuring
        description: The dark undershirt wobbles.
        match_state: match
        online_offline: offline
        ont_id: 10
        protect_side: 'yes'
        run_state: online
        sn: M7O64TY764QQ8FXS
      - config_state: normal
        control_flag: active
        description: The wary modernist crosses.
        match_state: initial
        online_offline: offline
        ont_id: 11
        protect_side: 'no'
        run_state: online
        sn: F6S33MMWVUE6X4LO
      - config_state: failing
        control_flag: configuring
        description: The drunk woodwind shops.
        match_state: mismatch
        online_offline: offline
        ont_id: 12
        protect_side: 'no'
        run_state: online
        sn: SM092BOB6OC7NIPG
      - config_state: normal
        control_flag: active
        description: The shrill networking accelerates.
        match_state: mismatch
        online_offline: online
        ont_id: 13
        protect_side: 'no'
        run_state: offline
        sn: 0WECQUOHRX1R2BB7
      - config_state: online
        control_flag: configuring
        description: The deafening rank installs.
        match_state: initial
        online_offline: online
        ont_id: 14
        protect_side: 'no'
        run_state: offline
        sn: MTQKSYNHT7JCBRYO
      - config_state: failing
        control_flag: configuring
        description: The blue shorts classifies.
        match_state: initial
        online_offline: online
        ont_id: 15
        protect_side: 'yes'
        run_state: offline
        sn: EKEMS4FTSA3JF3DC
    - - config_state: online
        control_flag: active
        description: The busy exposure visits.
        match_state: match
        online_offline: offline
        ont_id: 0
        protect_side: 'no'
        run_state: online
        sn: MIUX39AMGUN9OEOE
      - config_state: normal
        control_flag: configuring
        description: The uncovered brushfire mistakes.
        match_state: match
        online_offline: offline
        ont_id: 1
        protect_side: 'no'
        run_state: offline
        sn: OZX6KHA75IW7R658
      - config_state: online
        control_flag: configuring
        description: The warm stockings addresses.
        match_state: mismatch
        online_offline: offline
        ont_id: 2
        protect_side: 'no'
        run_state: offline
        sn: PDQN4GBGJBDZN1WF
      - config_state: online
        control_flag: active
        description: The historical pit sprouts.
        match_state: match
        online_offline: online
        ont_id: 3
        protect_side: 'no'
        run_state: offline
        sn: OAB52O6TB3351T9O
      - config_state: normal
        control_flag: configuring
        description: The fierce cell returns.
        match_state: match
        online_offline: offline
        ont_id: 4
        protect_side: 'no'
        run_state: online
        sn: LSITSR2XE4Y4JAIL
      - config_state: failing
        control_flag: active
        description: The poised decongestant says.
        match_state: initial
        online_offline: online
        ont_id: 5
        protect_side: 'yes'
        run_state: offline
        sn: Q6MZXA92KGBTE67B
      - config_state: failing
        control_flag: active
        description: The cruel gamma-ray beholds.
        match_state: initial
        online_offline: online
        ont_id: 6
        protect_side: 'yes'
        run_state: offline
        sn: ZUK43XUJLXL5JK5P
      - config_state: failing
        control_flag: configuring
        description: The dry pantyhose apologizes.
        match_state: initial
        online_offline: online
        ont_id: 7
        protect_side: 'yes'
        run_state: online
        sn: ZTRWHRL8T24QP8HN
      - config_state: failing
        control_flag: active
        description: The impossible copywriter practices.
        match_state: initial
        online_offline: online
        ont_id: 8
        protect_side: 'no'
        run_state: online
        sn: GRF3L52CQ2CZIIMW
      - config_state: normal
        control_flag: configuring
        description: The adventurous scent comes.
        match_state: initial
        online_offline: offline
        ont_id: 9
        protect_side: 'no'
        run_state: online
        sn: OT2BC66IUL2H1WNS
      - config_state: normal
        control_flag: configuring
        description: The abrasive distribution achieves.
        match_state: mismatch
        online_offline: offline
        ont_id: 10
        protect_side: 'yes'
        run_state: offline
        sn: 6TQGUCZI6UG5D0SU
      - config_state: failing
        control_flag: configuring
        description: The fair interval talks.
        match_state: initial
        online_offline: online
        ont_id: 11
        protect_side: 'no'
        run_state: online
        sn: SIUJ8YFUV715DARB
      - config_state: online
        control_flag: configuring
        description: The heavenly soccer attains.
        match_state: initial
        online_offline: offline
        ont_id: 12
        protect_side: 'yes'
        run_state: online
        sn: 1CDQWRXIGYZ9I3OW
      - config_state: online
        control_flag: active
        description: The strange cartoon plans.
        match_state: mismatch
        online_offline: online
        ont_id: 13
        protect_side: 'yes'
        run_state: offline
        sn: MZBKBMF5XSKR2U5T
      - config_state: failing
        control_flag: active
        description: The vivacious pea collects.
        match_state: mismatch
        online_offline: offline
        ont_id: 14
        protect_side: 'yes'
        run_state: online
        sn: XVBWN4Y2163F02BC
      - config_state: normal
        control_flag: active
        description: The jobless toga sweats.
        match_state: match
        online_offline: offline
        ont_id: 15
        protect_side: 'no'
        run_state: offline
        sn: KYIMITVJBQH72CWN
    - - config_state: normal
        control_flag: configuring
        description: The guttural crane plays.
        match_state: mismatch
        online_offline: offline
        ont_id: 0
        protect_side: 'no'
        run_state: offline
        sn: RAJ2219T743O5BZT
      - config_state: normal
        control_flag: configuring
        description: The screeching tamale devises.
        match_state: initial
        online_offline: online
        ont_id: 1
        protect_side: 'no'
        run_state: online
        sn: V96JNE9GJTVXDYUY
      - config_state: failing
        control_flag: configuring
        description: The aboard sadness upgrades.
        match_state: mismatch
        online_offline: offline
        ont_id: 2
        protect_side: 'yes'
        run_state: online
        sn: EJIXEFDP8YTOTDUA
      - config_state: normal
        control_flag: configuring
        description: The abject discrimination rhymes.
        match_state: match
        online_offline: offline
        ont_id: 3
        protect_side: 'no'
        run_state: online
        sn: OUZI4FN2PUC01PHK
      - config_state: normal
        control_flag: active
        description: The royal dungeon skis.
        match_state: mismatch
        online_offline: online
        ont_id: 4
        protect_side: 'yes'
        run_state: online
        sn: 3ZMEBZVNQNQA1GGY
      - config_state: normal
        control_flag: configuring
        description: The cool allocation phones.
        match_state: match
        online_offline: online
        ont_id: 5
        protect_side: 'no'
        run_state: offline
        sn: G9OZJXOX502LCRHZ
      - config_state: failing
        control_flag: active
        description: The half document translates.
        match_state: match
        online_offline: online
        ont_id: 6
        protect_side: 'no'
        run_state: online
        sn: 1A4EF1I9MSAEQ367
      - config_state: normal
        control_flag: active
        description: The fluffy investment saws.
        match_state: initial
        online_offline: offline
        ont_id: 7
        protect_side: 'no'
        run_state: online
        sn: NYU6ZOSE67NKWN29
      - config_state: failing
        control_flag: configuring
        description: The lackadaisical prisoner likes.
        match_state: match
        online_offline: online
        ont_id: 8
        protect_side: 'no'
        run_state: offline
        sn: JEGA5SG66EXB0Q6A
      - config_state: online
        control_flag: configuring
        description: The stupid draw grips.
        match_state: initial
        online_offline: offline
        ont_id: 9
        protect_side: 'no'
        run_state: offline
        sn: MIQRF9NRN6LLE1YH
      - config_state: normal
        control_flag: configuring
        description: The numberless antiquity shivers.
        match_state: mismatch
        online_offline: offline
        ont_id: 10
        protect_side: 'no'
        run_state: offline
        sn: J1YLLSYGIVWO6D2Z
      - config_state: failing
        control_flag: active
        description: The omniscient commodity proves.
        match_state: match
        online_offline: offline
        ont_id: 11
        protect_side: 'no'
        run_state: offline
        sn: 9JUECSEA67ESHGCX
      - config_state: normal
        control_flag: configuring
        description: The hesitant pretzel loses.
        match_state: match
        online_offline: offline
        ont_id: 12
        protect_side: 'no'
        run_state: online
        sn: C9JY73JJXYS748VE
      - config_state: failing
        control_flag: configuring
        description: The noisy tatami vanishes.
        match_state: mismatch
        online_offline: online
        ont_id: 13
        protect_side: 'yes'
        run_state: online
        sn: B4DUEMC4FR8EAR41
      - config_state: normal
        control_flag: configuring
        description: The icy elbow records.
        match_state: initial
        online_offline: online
        ont_id: 14
        protect_side: 'yes'
        run_state: offline
        sn: UPNFAVO8UNGTHEFN
      - config_state: normal
        control_flag: active
        description: The joyous waiter prescribes.
        match_state: match
        online_offline: offline
        ont_id: 15
        protect_side: 'yes'
        run_state: online
        sn: YMY8Y3HHTERKPP6Z
    slotid: 2
    status: Normal
    subtype0: ''
    subtype1: ''
  - boardname: A123ABCD
    online_offline: ''
    slotid: 3
    status: Active_normal
    subtype0: CPCF
    subtype1: ''
  - boardname: A123ABCD
    online_offline: Offline
    slotid: 4
    status: Standby_failed
    subtype0: CPCF
    subtype1: ''
  - boardname: ''
    online_offline: ''
    slotid: 5
    status: ''
    subtype0: ''
    subtype1: ''
