frames:
- frame_id: 0
  slots:
  - boardname: A123ABCD
    online_offline: ''
    slotid: 0
    status: Normal
    subtype0: ''
    subtype1: ''
  - boardname: ''
    online_offline: ''
    slotid: 1
    status: ''
    subtype0: ''
    subtype1: ''
  - boardname: H901GPSFE
    online_offline: ''
    ports: []
    slotid: 2
    status: Normal
    subtype0: ''
    subtype1: ''
  - boardname: A123ABCD
    online_offline: ''
    slotid: 3
    status: Active_normal
    subtype0: CPCF
    subtype1: ''
  - boardname: A123ABCD
    online_offline: Offline
    slotid: 4
    status: Standby_failed
    subtype0: CPCF
    subtype1: ''
  - boardname: ''
    online_offline: ''
    slotid: 5
    status: ''
    subtype0: ''
    subtype1: ''
